### PR TITLE
Change to using submodules

### PR DESCRIPTION
**Pull request by 8BitJosh**
- Move away from repo to using git submodules instead
- Add scripts to install dependecies
- Update script to symlink the config files to the correct location
- Added gitignore for the files created by bitbake
- Update README with instructions

### CODE REVIEW

**Comment by 8BitJosh** [comment]
Updated to include the generation of the SD card image by swapping kernel etc...

**Comment by trickeydan** [comment]
Code looks fine. I have yet to run a build, but will do later today.

I am unsure about committing the pre-compiled kernel modules to the repo as they are huge. Especially as we won't be using the ODROIDs for much longer. Unfortunately as ALARM removed the  5.11 modules we can't download them from there.

Any ideas as an alternative other than just downloading the latest files that ALARM publish?

**Comment by trickeydan** [comment]
Screenshot 2022-02-20 at 12 15 39

`setup.sh` doesn't seem to work on Ubuntu 18.04? Which distros do you mean by "apt-based"?

Also, setup.sh probably needs `set -e` as it continued to run even when APT failed in above screenshot.

**Comment by 8BitJosh** [comment]
That list of dependecies comes from the [yocto website](https://www.yoctoproject.org/docs/2.4.2/yocto-project-qs/yocto-project-qs.html#packages), I am also using Ubuntu 20.04 Desktop and it works fine, are you using Ubuntu server

**Comment by 8BitJosh** [comment]
I agree I was unkeen about adding the kernel bits but was unsure where to get them from, I could change it to be a zip (its about 50MB), and make the script extract them in the right place when needed.

**Comment by raccube** [comment]
I have tried this out locally and it appears to have built fine (haven't checked out the image itself). I think it's all fine, although I did get confused by the setup steps in the readme.

It mentions creating a directory called `srobo-build` and cloning this repo inside of there, making it create a subdirectory called `robot-image-build-config`. I think think this should actually be replaced with `git clone <this repo url> srobo-build`.

The `assemble.sh` script assumes that the PWD is in the build directory as it makes use of relative paths. This can probably be changed to use paths relative to the script itself or variables set by `setup-env.sh`.

I also feel a bit iffy about pulling in odroid vendor stuff.

**Comment by raccube** [comment]
Just checked out the built image and it seems all good.

**Comment by WillB97** [comment]
We could move the kernel files into a zip attached to a release on this repo that we pull down in `setup.sh`.

**Comment by raccube** [comment]
Honestly it doesn't really matter as we're moving to Raspberry Pi immediately after this anyway.

**Comment by trickeydan** [comment]
Proposal: We rip the kernel files out of this PR and merge it. The new `main` branch will build, but it won't work on an ODROID. We can then begin on porting to RPi on a single repo setup?

**Comment by raccube** [comment]
We'll be making a release with all of the stuff needed to build the old image so that it's not lost.

**Comment by WillB97** [comment]
We'll make a release on meta-odroid-u3 as it stands and put the kernel files on that release. Then the kernel files can be removed from here.

**Review by trickeydan — APPROVED** [review]

**Pull request merged**
